name: release-alioth-builder-fd

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE_1:
        description: 'Kernel Tree'
        default: 'https://github.com/re-noroi/kernel_sm8250'
        required: true
      CODENAME:
        description: 'Phone Codename'
        default: 'alioth'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/re-noroi/anykernel3-test'
        required: false
      CUSTOM_SED:
        description: 'Custom Kernel Version'
        default: '-Yosaki-Sonako'
        required: false
      COMPILER:
        description: 'default=neutron, write aosp for aosp 20 clang'
        default: 'neutron'
        required: false
      kernelsu_version:
        description: 'KernelSU Version'
        required: true
        type: choice
        default: 'rksu'
        options:
          - 'sukisu-ultra'
          - 'ksu'
          - 'rksu'
          - 'sukisu'
          - 'noksu'

jobs:
  build:
    strategy:
      matrix:
        kernel: [1, 2]
    runs-on: ubuntu-latest
    env:
      UPLOAD_TO_RELEASE: false

    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Download & Extract Clang
        run: |
          if [[ "${{ github.event.inputs.COMPILER }}" == "aosp" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          else
            wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
            mkdir clang
            unzstd -d clang.tar.zst
            tar -xf clang.tar -C clang
          fi
          
      - name: Set Kernel Environment Variables
        run: |
          echo "KERNEL_TREE=${{ github.event.inputs.KERNEL_TREE_1 }}" >> $GITHUB_ENV
          case "${{ matrix.kernel }}" in
            1) echo "KERNEL_TREE_BRANCH=no-ksu" >> $GITHUB_ENV ;;
            2) echo "KERNEL_TREE_BRANCH=freesia" >> $GITHUB_ENV ;;
          esac
         
      - name: Checkout Kernel via PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ "${{ github.event.inputs.KERNEL_TREE_1 }}" == "private" ]]; then
            REPO_URL="https://x-access-token:${GH_PAT}@github.com/re-noroi/FD-private.git"
          else
            REPO_URL="${{ github.event.inputs.KERNEL_TREE_1 }}"
          fi
          git clone --depth=1 --branch "${{ env.KERNEL_TREE_BRANCH }}" "${REPO_URL}" kernel_tree

      - name: Kernel Version
        run: |
          cd kernel_tree
          if [[ "${{ github.event.inputs.CUSTOM_SED }}" != "-Yosaki-Sonako" ]]; then
            sed -i -e 's/CONFIG_LOCALVERSION="-Yosaki-Sonako"/CONFIG_LOCALVERSION="${{ github.event.inputs.CUSTOM_SED }}"/' arch/arm64/configs/vendor/alioth_defconfig
          fi

      - name: Change different battery type
        if: matrix.kernel == 1 || matrix.kernel == 2
        run: |
          cd kernel_tree
          sed -i -e '/qcom,j3s-batt-profile;/d' arch/arm64/boot/dts/vendor/qcom/alioth-sm8250.dtsi

      - name: Revert to stock gpufreq
        if: matrix.kernel == 1 || matrix.kernel == 2
        run: |
          cd kernel_tree
          patch -p1 -f < "0001-stock-gpu-freq.patch"

      - name: Apply Modifications (if modified build)
        if: matrix.kernel == 2
        run: |
          cd kernel_tree
          sed -i -e '/<2553600>,/c\<2553600>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2649600>,/c\//<2649600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2745600>,/c\//<2745600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2841600>,/c\//<2841600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<3187200>;/c\//<3187200>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-width-dimension = <70>;/qcom,mdss-pan-physical-width-dimension = <695>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-height-dimension = <155>;/qcom,mdss-pan-physical-height-dimension = <1546>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi

      - name: Add KernelSU based on selection
        run: |
          cd kernel_tree
          KSU_VERSION="${{ github.event.inputs.kernelsu_version }}"
          ADDITIONAL="${{ github.event.inputs.additional_function }}"
          SuSFS_ENABLE=0
          if [[ "$ADDITIONAL" == "susfs" || "$ADDITIONAL" == "susfs-kpm" ]]; then
            SuSFS_ENABLE=1
          fi

          if [ "$KSU_VERSION" == "ksu" ]; then
            echo "KSU is enabled"
            if [ "$SuSFS_ENABLE" -eq 1 ]; then
              echo "::error::Official KernelSU does not support SuSFS. Build failed."
              exit 1
            fi
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
          elif [ "$KSU_VERSION" == "rksu" ]; then
            if [ "$SuSFS_ENABLE" -eq 1 ]; then
              echo "RKSU && SuSFS is enabled"
              curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s susfs-v1.5.5
            else
              echo "RKSU is enabled"
              curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
            fi
          elif [ "$KSU_VERSION" == "sukisu" ]; then
            if [ "$SuSFS_ENABLE" -eq 1 ]; then
              echo "SukiSU && SuSFS is enabled"
              curl -LSs "https://raw.githubusercontent.com/ShirkNeko/KernelSU/main/kernel/setup.sh" | bash -s susfs-dev
            else
              echo "SukiSU is enabled"
              curl -LSs "https://raw.githubusercontent.com/ShirkNeko/KernelSU/main/kernel/setup.sh" | bash -s dev
            fi
          elif [ "$KSU_VERSION" == "sukisu-ultra" ]; then
            if [ "$SuSFS_ENABLE" -eq 1 ]; then
              echo "SukiSU-Ultra && SuSFS is enabled"
              curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            else
              echo "SukiSU-Ultra is enabled"
              curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s nongki
            fi
          else
            echo "KernelSU integration is skipped."
          fi
      
      - name: Build Kernel
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="sonako"
          export KBUILD_BUILD_HOST="yski"
          export KBUILD_BUILD_TIMESTAMP="$(TZ=UTC-8 date)"
          cd kernel_tree
          make O=out vendor/alioth_defconfig
          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
          if [[ "${{ matrix.kernel }}" == 1 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtbo.img ../alioth-j3s-dtbo-aosp.img
            mv out/arch/arm64/boot/dtb.img ../alioth-normal-dtb
          elif [[ "${{ matrix.kernel }}" == 2 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtbo.img ../alioth-j3s-dtbo-miui.img
            mv out/arch/arm64/boot/dtb.img ../alioth-effcpu-dtb
          else
            mv out/arch/arm64/boot/dtb.img ../alioth-effcpu-gpustk-dtb
            mv out/arch/arm64/boot/dtbo.img ../alioth-stock-dtbo-miui.img
          fi

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel != 2
        with:
          name: kernel-${{ matrix.kernel }}-base
          path: |
            Image.gz

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 1
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            alioth-j3s-dtbo-aosp.img
            alioth-normal-dtb

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 2
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            alioth-j3s-dtbo-miui.img
            alioth-effcpu-dtb
            
  package_anykernel:
    needs: build
    strategy:
      matrix:
        kernel: [1]
    runs-on: ubuntu-latest

    steps:
      - name: Download Kernel Build Image
        uses: actions/download-artifact@v4
        with:
          name: kernel-${{ matrix.kernel }}-base
          path: kernel-${{ matrix.kernel }}-base

      - name: Download Kernel Build Addon 1
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-1-addon
          path: kernel-part-1-addon

      - name: Download Kernel Build Addon 2
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-2-addon
          path: kernel-part-2-addon

      - name: Clone AnyKernel3
        run: git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b main AnyKernel3-${{ matrix.kernel }}

      - name: Move Kernel Files to AnyKernel3
        run: |
          mv kernel-${{ matrix.kernel }}-base/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-1-addon/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-2-addon/* AnyKernel3-${{ matrix.kernel }}/

      - name: Define ZIP Name
        run: |
          KSU_VERSION="${{ github.event.inputs.kernelsu_version }}"
          COMPILED_DATE=$(date +%Y%m%d)
          
          KSU_ZIP_STR="NoKSU"
          if [ "$KSU_VERSION" == "ksu" ]; then KSU_ZIP_STR="KSU"; fi
          if [ "$KSU_VERSION" == "rksu" ]; then KSU_ZIP_STR="RKSU"; fi
          if [ "$KSU_VERSION" == "sukisu" ]; then KSU_ZIP_STR="SukiSU"; fi
          if [ "$KSU_VERSION" == "sukisu-ultra" ]; then KSU_ZIP_STR="SukiSU-Ultra"
          COMPILED_DATE=$(date +%Y%m%d)
          ADD_FUNC_STR=""

          ZIP_NAME="[kernel-${KSU_ZIP_STR}][-${{ github.event.inputs.CODENAME }}-${COMPILED_DATE}]"
          echo "Final ZIP name: ${ZIP_NAME}"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      
      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            AnyKernel3-${{ matrix.kernel }}/
            !AnyKernel3-${{ matrix.kernel }}/.git
            !AnyKernel3-${{ matrix.kernel }}/.github
      
