name: FD-release-alioth-builder

on:
  pull_request:
  workflow_dispatch:
    inputs:
      KERNEL_TREE_1:
        description: 'Kernel Tree'
        default: 'https://github.com/re-noroi/kernel_sm8250'
        required: true
      CODENAME:
        description: 'Phone Codename'
        default: 'alioth'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/re-noroi/anykernel3-test'
        required: false
      CUSTOM_SED:
        description: 'Custom Kernel Version'
        default: '-Yski-Sonako'
        required: false
      COMPILER:
        description: 'Choose compiler'
        required: true
        type: choice
        options:
          - neutron
          - aosp
          - aosp-21
        default: neutron
      Rekernel:
        description: 'Enable rekernel(tks patch for prslc)'
        required: true
        type: choice
        options:
          - enable
          - disable
      kernelsu_version:
        description: 'KernelSU Version'
        required: true
        type: choice
        default: 'rksu'
        options:
          - 'sukisu-ultra'
          - 'ksu'
          - 'rksu'
          - 'sukisu'
          - 'noksu'
      Additional_function:
        description: 'Additional Functions'
        required: true
        type: choice
        default: 'no'
        options:
          - 'no'
          - 'kpm'
      LTO_CHOICE:
        required: true
        type: choice
        options:
          - full_lto
          - thin_lto
        default: full_lto

jobs:
  build:
    strategy:
      matrix:
        kernel: [1, 2, 3]
    runs-on: ubuntu-latest
    env:
      UPLOAD_TO_RELEASE: false

    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Download & Extract Clang
        run: |
          if [[ "${{ github.event.inputs.COMPILER }}" == "aosp" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          elif [[ "${{ github.event.inputs.COMPILER }}" == "aosp-21" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/603a89415bbb04dff8bc577b95534479ec13fdc5/clang-r574158.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          else
            wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
            mkdir clang
            unzstd -d clang.tar.zst
            tar -xf clang.tar -C clang
          fi
          
      - name: Set Kernel Environment Variables
        run: |
          echo "KERNEL_TREE=${{ github.event.inputs.KERNEL_TREE_1 }}" >> $GITHUB_ENV
          case "${{ matrix.kernel }}" in
            1) echo "KERNEL_TREE_BRANCH=next-main" >> $GITHUB_ENV ;;
            2) echo "KERNEL_TREE_BRANCH=next-susfs" >> $GITHUB_ENV ;;
            3) echo "KERNEL_TREE_BRANCH=no-ksu" >> $GITHUB_ENV ;;
          esac
         
      - name: Checkout Kernel via PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ "${{ github.event.inputs.KERNEL_TREE_1 }}" == "private" ]]; then
            REPO_URL="https://x-access-token:${GH_PAT}@github.com/re-noroi/FD-private.git"
          else
            REPO_URL="${{ github.event.inputs.KERNEL_TREE_1 }}"
          fi
          git clone --depth=1 --branch "${{ env.KERNEL_TREE_BRANCH }}" "${REPO_URL}" kernel_tree

      - name: Kernel Version
        run: |
          cd kernel_tree
          if [[ "${{ github.event.inputs.CUSTOM_SED }}" != "-FakeDreamer" ]]; then
            sed -i -e 's/CONFIG_LOCALVERSION="-FakeDreamer"/CONFIG_LOCALVERSION="${{ github.event.inputs.CUSTOM_SED }}"/' arch/arm64/configs/vendor/alioth_defconfig
          fi
      
      - name: Apply Patches (Skip for Kernel 1 or 3)
        if: matrix.kernel != 1 && matrix.kernel != 3
        run: |
          cd kernel_tree
          bash nextpatch.sh

      - name: Patch Kernel of Re:Kernel
        if: github.event.inputs.Rekernel == 'enable'
        run: |
          cd kernel_tree
          PATCH_FILE="/tmp/Patches/Rekernel/4.19_rekernel_full_alioth-fd.patch"

          if [ -f "$PATCH_FILE" ]; then
            cp /tmp/Patches/Rekernel/4.19_rekernel_full_alioth-fd.patch ./
            patch -p1 < 4.19_rekernel_full_alioth-fd.patch || true
            echo "Re:Kernel Patched."
          fi

      - name: Change different battery type
        if: matrix.kernel == 3
        run: |
          cd kernel_tree
          sed -i -e '/qcom,j3s-batt-profile;/d' arch/arm64/boot/dts/vendor/qcom/alioth-sm8250.dtsi

      - name: Revert to stock gpufreq
        if: matrix.kernel == 3
        run: |
          cd kernel_tree
          patch -p1 -f < "0001-stock-gpu-freq.patch"

      - name: Change LTO Type
        if: ${{ github.event.inputs.LTO_CHOICE == 'thin_lto' }}
        run: |
          cd kernel_tree
          sed -i -e '/# CONFIG_LTO_CLANG_THIN is not set/c\CONFIG_LTO_CLANG_THIN=y;' arch/arm64/configs/vendor/alioth_defconfig
          sed -i -e '/CONFIG_LTO_CLANG_FULL=y/c\# CONFIG_LTO_CLANG_FULL is not set;' arch/arm64/configs/vendor/alioth_defconfig
        
      - name: Add KernelSU based on selection
        if: matrix.kernel != 3
        run: |
          cd kernel_tree
          KSU_VERSION="${{ github.event.inputs.kernelsu_version }}"
          ADDITIONAL="${{ github.event.inputs.additional_function }}"

          if [ "$KSU_VERSION" == "ksu" ]; then
            curl -LSs "https://raw.githubusercontent.com/Prslc/KernelSU/main/kernel/setup.sh" | bash -s nongki
          elif [ "$KSU_VERSION" == "rksu" ]; then
              echo "RKSU is enabled"
              curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
          elif [ "$KSU_VERSION" == "sukisu" ]; then
              echo "SukiSU is enabled"
              curl -LSs "https://raw.githubusercontent.com/ShirkNeko/KernelSU/main/kernel/setup.sh" | bash -s dev
          elif [ "$KSU_VERSION" == "sukisu-ultra" ]; then
              echo "SukiSU-Ultra is enabled"
              curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s nongki
          else
            echo "KernelSU integration is skipped."
          fi
          
      - name: Apply Modifications (if modified build)
        if: matrix.kernel == 2
        run: |
          cd kernel_tree
          sed -i -e '/<2553600>,/c\<2553600>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2649600>,/c\//<2649600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2745600>,/c\//<2745600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2841600>,/c\//<2841600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<3187200>;/c\//<3187200>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-width-dimension = <70>;/qcom,mdss-pan-physical-width-dimension = <695>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-height-dimension = <155>;/qcom,mdss-pan-physical-height-dimension = <1546>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
      
      - name: Build Kernel
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="sonako"
          export KBUILD_BUILD_HOST="yosaki"
          export KBUILD_BUILD_TIMESTAMP="$(TZ=UTC-8 date)"
          cd kernel_tree
          ADDITIONAL="${{ github.event.inputs.additional_function }}"

          # If you choose to turn on kpm, kpm will be enabled in config
          if [[ "$ADDITIONAL" == "kpm" && "${{ matrix.kernel }}" == "1" ]]; then
          echo "Enabling KPM required kernel configurations in vendor/alioth_defconfig using sed..."
          
          DEFCONFIG_FILE="arch/arm64/configs/vendor/alioth_defconfig"
          sed -i \
            -e 's/^# CONFIG_KPM is not set/CONFIG_KPM=y/' \
            -e 's/^CONFIG_KPM=n/CONFIG_KPM=y/' \
            "$DEFCONFIG_FILE"
          if ! grep -q "^CONFIG_KPM\|^# CONFIG_KPM" "$DEFCONFIG_FILE"; then
              echo "CONFIG_KPM=y" >> "$DEFCONFIG_FILE"
              echo "INFO: CONFIG_KPM was missing and has been appended."
          fi
          
          sed -i \
            -e 's/^# CONFIG_KALLSYMS is not set/CONFIG_KALLSYMS=y/' \
            -e 's/^CONFIG_KALLSYMS=n/CONFIG_KALLSYMS=y/' \
            "$DEFCONFIG_FILE"
          if ! grep -q "^CONFIG_KALLSYMS\|^# CONFIG_KALLSYMS" "$DEFCONFIG_FILE"; then
              echo "CONFIG_KALLSYMS=y" >> "$DEFCONFIG_FILE"
              echo "INFO: CONFIG_KALLSYMS was missing and has been appended."
          fi

          sed -i \
            -e 's/^# CONFIG_KALLSYMS_ALL is not set/CONFIG_KALLSYMS_ALL=y/' \
            -e 's/^CONFIG_KALLSYMS_ALL=n/CONFIG_KALLSYMS_ALL=y/' \
            "$DEFCONFIG_FILE"
          if ! grep -q "^CONFIG_KALLSYMS_ALL\|^# CONFIG_KALLSYMS_ALL" "$DEFCONFIG_FILE"; then
              echo "CONFIG_KALLSYMS_ALL=y" >> "$DEFCONFIG_FILE"
              echo "INFO: CONFIG_KALLSYMS_ALL was missing and has been appended."
          fi
          
          echo "KPM kernel configurations enabled in $DEFCONFIG_FILE."
          fi
          
          make O=out vendor/alioth_defconfig
          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
          # Patching kpm
          if [[ "$ADDITIONAL" == "kpm" && "${{ matrix.kernel }}" == "1" ]]; then
          echo "Detected KPM enabled for Kernel 1, applying patches..."
          pushd out/arch/arm64/boot
        
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch
          chmod +x patch
          ./patch
          
          if [ $? -eq 0 ]; then
            rm -f Image
            mv oImage Image
            gzip -f Image
            echo "The KPM patch was successfully applied, Image was repaired and re-compressed to Image.gz."
          else
            echo "::warning::KPM patch application failed, original image file will be used."
          fi
          popd
          else
          echo "KPM is not enabled (${{ env.KPM_ENABLE }}), skipping patching process."
          fi
        
          if [[ "${{ matrix.kernel }}" == 1 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtbo.img ../alioth-j3s-dtbo-aosp.img
            mv out/arch/arm64/boot/dtb.img ../alioth-normal-dtb
          elif [[ "${{ matrix.kernel }}" == 2 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtbo.img ../alioth-j3s-dtbo-miui.img
            mv out/arch/arm64/boot/dtb.img ../alioth-effcpu-dtb
          elif [[ "${{ matrix.kernel }}" == 3 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtb.img ../alioth-normal-gpustk-dtb
            mv out/arch/arm64/boot/dtbo.img ../alioth-stock-dtbo-aosp.img
          else
            mv out/arch/arm64/boot/dtb.img ../alioth-effcpu-gpustk-dtb
            mv out/arch/arm64/boot/dtbo.img ../alioth-stock-dtbo-miui.img
          fi
          
      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ matrix.kernel }}-base
          path: |
            Image.gz

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 1
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            alioth-j3s-dtbo-aosp.img
            alioth-normal-dtb

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 2
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            alioth-j3s-dtbo-miui.img
            alioth-effcpu-dtb

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 3
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            alioth-stock-dtbo-aosp.img
            alioth-normal-gpustk-dtb

  package_anykernel:
    needs: build
    strategy:
      matrix:
        kernel: [1, 2, 3]
    runs-on: ubuntu-latest

    steps:
      - name: Download Kernel Build Image
        uses: actions/download-artifact@v4
        with:
          name: kernel-${{ matrix.kernel }}-base
          path: kernel-${{ matrix.kernel }}-base

      - name: Download Kernel Build Addon 1
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-1-addon
          path: kernel-part-1-addon

      - name: Download Kernel Build Addon 2
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-2-addon
          path: kernel-part-2-addon

      - name: Download Kernel Build Addon 3
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-3-addon
          path: kernel-part-3-addon

      - name: Clone AnyKernel3
        run: git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b main AnyKernel3-${{ matrix.kernel }}

      - name: Move Kernel Files to AnyKernel3
        run: |
          mv kernel-${{ matrix.kernel }}-base/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-1-addon/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-2-addon/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-3-addon/* AnyKernel3-${{ matrix.kernel }}/

      - name: Define ZIP Name
        run: |
          COMPILED_DATE=$(date +%Y%m%d)
          if [[ "${{ matrix.kernel }}" == "1" ]]; then
            echo "ZIP_NAME=[FD-][ksu-${{ github.event.inputs.CODENAME }}-$COMPILED_DATE]" >> $GITHUB_ENV
          elif [[ "${{ matrix.kernel }}" == "2" ]]; then
            echo "ZIP_NAME=[FD-][susfs-${{ github.event.inputs.CODENAME }}-$COMPILED_DATE]" >> $GITHUB_ENV
          else
            echo "ZIP_NAME=[FD-][noksu-${{ github.event.inputs.CODENAME }}-$COMPILED_DATE]" >> $GITHUB_ENV
          fi
      
      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            AnyKernel3-${{ matrix.kernel }}/
            !AnyKernel3-${{ matrix.kernel }}/.git
            !AnyKernel3-${{ matrix.kernel }}/.github
      
